// Generated by CoffeeScript 1.9.3
(function() {
  var KEY, _, express, http, parser, router;

  express = require('express');

  router = express.Router();

  parser = require('xml2json');

  http = require('http');

  _ = require('lodash');

  KEY = 'Q2VM-JDUP-IMPQ-DT35';

  router.get('/', function(req, rsp, next) {
    return http.get("http://api.bart.gov/api/etd.aspx?cmd=etd&orig=12th&key=" + KEY + "&dir=s", function(res) {
      var body;
      body = '';
      res.on('data', function(chunk) {
        return body += chunk;
      });
      return res.on('end', function() {
        var data;
        data = JSON.parse(parser.toJson(body));
        data = data['root'];
        data['station']['etd'] = _.reject(data['station']['etd'], function(etd) {
          return etd.abbreviation === 'FRMT';
        });
        _.each(data['station']['etd'], function(etd) {
          return etd['estimate'] = _.map(etd['estimate'], function(estimate) {
            return _.pick(estimate, ['minutes', 'length']);
          });
        });
        delete data.uri;
        rsp.setHeader('content-type', 'application/json');
        return rsp.send(JSON.stringify(data));
      });
    }).on('error', function(e) {
      return console.log("Got error: " + e.message);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=schedule.js.map
