// Generated by CoffeeScript 1.8.0
(function() {
  var KEY, express, parser, router;

  express = require('express');

  router = express.Router();

  parser = require('xml2json');

  KEY = 'Q2VM-JDUP-IMPQ-DT35';

  router.get('/', function(req, res, next) {
    var json, xml;
    xml = "<foo>bar</foo>";
    json = parser.toJson(xml);
    console.log(json);
    return res.send('respond with a resource');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=schedule.js.map
